### ISSUE TITLE
keep gettings this error

### ISSUE THREAD

**Issue by gagrecco** [JordanZeotni/BotW-Save-Manager#9] opened 2020-09-17 05:50 UTC
I am trying to convert my switch file. I imported it from myswitch. It works on yuzu even. 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at BotWSaveManager.UI.MainForm.OpenSaveToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Users\thegr\Source\Repos\DeltaJordan\BotW-Save-Manager\BotWSaveManager.UI\MainForm.cs:line 114
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
BotWSaveManager.UI
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/gagre/Desktop/save/BotWSaveManager-1.1.3-WindowsUI/BotWSaveManager.UI.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
NLog
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.0.9261
    CodeBase: file:///C:/Users/gagre/Desktop/save/BotWSaveManager-1.1.3-WindowsUI/NLog.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
BotWSaveManager.Conversion
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/gagre/Desktop/save/BotWSaveManager-1.1.3-WindowsUI/BotWSaveManager.Conversion.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by MhzDev** [comment] 2020-09-26 17:40
Same exact crash for me, switch savegame

**Comment by DeltaJordan** [comment] 2020-10-08 17:27
> 
> 
> [16-09-20-7.log](https://github.com/DeltaJordan/BotW-Save-Manager/files/5236135/16-09-20-7.log)
> [16-09-20-2.log](https://github.com/DeltaJordan/BotW-Save-Manager/files/5236136/16-09-20-2.log)
> 
> PLEASE please help me my good man. Ill be very thankful

Moved from #8.

**Comment by DeltaJordan** [comment] 2020-10-08 17:32
I'm not too sure what the issue is here. The stacktrace you posted in this issue suggests you did not enter a path in the directory selector:

```
at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
at BotWSaveManager.UI.MainForm.OpenSaveToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Users\thegr\Source\Repos\DeltaJordan\BotW-Save-Manager\BotWSaveManager.UI\MainForm.cs:line 114
```

I doubt this is the root of the issue you are having with the application. Both the logs you posted in the other issue also indicate no errors. For now, I will be merging a pull request to add support for version 1.6, perhaps that release could solve your issue.

**Comment by DeltaJordan** [comment] 2020-10-08 17:42
This is a duplicate of #6, and will be fixed in the next release. If the issue persists, please create a new issue.

**Closed as completed** 2020-10-08 17:43 UTC
Labels: duplicate

**Comment by MhzDev** [comment] 2020-10-08 19:56
@DeltaJordan Fixed for me! I was using one of the latest zelda update
